name: Checks
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

permissions:
  contents: read
  pull-requests: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: '8.0'
          mongodb-replica-set: rs0
      - name: Install
        run: |
          npm install
      - name: Lint
        run: |
          npm run lint
      - name: Audit
        run: |
          npm run audit
      - name: Test
        run: |
          npm test
      - name: Build
        run: |
          npm run build
